c="Celebration Calls"
print(c.upper())
print(c.title())
print(c.lower())
print(c.lstrip())
print(c.rstrip())
print(c.find("br"))
print(c.replace("a","o"))
print(c.replace("C","D"))
print("le" in c)
print("we" not in c)
